version: '3'

services:
  hellonestapp:
    #depends_on:
    #  - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: metodos-pago-docker
    container_name: metodospagoapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/metodos_pago
    environment:
      #MONGODB: ${MONGODB}
      PORT: ${PORT}
      #DEFAULT_LIMIT: ${DEFAULT_LIMIT}
    # volumes:
    #   - ./:/var/www/metodos_pago

  #db:
  #  image: mongo:5
  #  container_name: mongo-metodos_pago
  #  restart: always
  #  ports:
  #    - 27017:27017
  #  environment:
  #    MONGODB_DATABASE: nest-metodos_pago
  #  # volumes:
    #   - ./mongo:/data/db